---
title: "Simon Steiger's CV"
author: Simon Steiger
date: "`r Sys.Date()`"
params:
  lang: "eng"
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  # ENG https://docs.google.com/spreadsheets/d/1Ol2mTJCFrY1hPBRjdpDoDNwdfsvdRGryLrOy6OYNKzY/edit#gid=0
  # SWE https://docs.google.com/spreadsheets/d/1UTJIz1DB3IqirKpPtkw4O7SoQvPpeW0O_58u-MHnO6Q/edit#gid=1816599202
  data_location = "https://docs.google.com/spreadsheets/d/1Ol2mTJCFrY1hPBRjdpDoDNwdfsvdRGryLrOy6OYNKzY/edit#gid=0",  
  pdf_mode = params$pdf_mode
)
```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
# if(params$pdf_mode){
#   cat("View this CV online with links at _nickstrayer.me/datadrivencv/_")
# } else {
#   cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/simonsteiger/cv/steiger_cv.pdf)")
# }
```

```{asis, echo = params$lang == "swe"}
Kontakt {#contact}
--------------------------------------------------------------------------------
```

```{asis, echo = params$lang == "eng"}
Contact {#contact}
--------------------------------------------------------------------------------
```

```{r}
CV %>% print_contact_info()
```


```{asis, echo = params$lang == "swe"}
Programmering {#skills}
--------------------------------------------------------------------------------
```

```{asis, echo = params$lang == "eng"}
Languages {#skills}
--------------------------------------------------------------------------------
```


```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

```{asis, echo = params$lang == "eng"}
Made with the R package [**pagedown**](https://github.com/rstudio/pagedown).

The source code is available [on github.com/simonsteiger/cv](https://github.com/simonsteiger/cv).
```

```{asis, echo = params$lang == "swe"}
Skapad med [**pagedown**](https://github.com/rstudio/pagedown).

Se source koden [på github.com/simonsteiger/cv](https://github.com/simonsteiger/cv).
```

`r Sys.Date()`

Main
================================================================================

Simon Steiger {#title}
--------------------------------------------------------------------------------

```{r, results='asis'}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 

cat("\n\nIn my free time, I keep my statistical skills fresh by working on research projects with my friends. Feel free to have a look at my GitHub page!")
```

```{asis, echo = params$lang == "swe"}
Utbildning {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------
```

```{asis, echo = params$lang == "eng"}
Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------
```

```{r}
CV %<>% print_section('education')
```

```{asis, echo = params$lang == "swe"}
Industri {data-icon=suitcase}
--------------------------------------------------------------------------------
```

```{asis, echo = params$lang == "eng"}
Industry {data-icon=suitcase}
--------------------------------------------------------------------------------
```

::: aside
```{r}
# CV %<>% print_text_block('industy_experience_aside')
```
:::

```{r}
CV %<>% print_section('industry_positions')
```

```{asis, echo = params$lang == "swe"}
Vetenskap {data-icon=laptop}
--------------------------------------------------------------------------------
```

```{asis, echo = params$lang == "eng"}
Research {data-icon=laptop}
--------------------------------------------------------------------------------
```

::: aside
```{r}
# CV %<>% print_text_block('research_positions_aside')
```
:::

```{r}
CV %<>% print_section('research_positions')
```

```{asis, echo = params$lang == "swe"}
Undervisning {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------
```

```{asis, echo = params$lang == "eng"}
Teaching {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------
```

::: aside
```{r}
# CV %<>% print_text_block('teaching_experience_aside')
```
:::

```{r}
CV %<>% print_section('teaching_positions')
```



<!-- Selected Data Science Writing {data-icon=chart-line} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ::: aside -->
<!-- ```{r} -->
<!-- CV %<>% print_text_block('data_science_writing_aside') -->
<!-- ``` -->
<!-- ::: -->

<!-- ```{r} -->
<!-- CV %<>% print_section('data_science_writings') -->
<!-- ``` -->



<!-- Selected Press (About)  {data-icon=newspaper} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('about_me_press') -->
<!-- ``` -->


<!-- <br> -->
<!-- <br> -->


<!-- Selected Press (By)  {data-icon=newspaper} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('by_me_press') -->
<!-- ``` -->



Publications {data-icon=book}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('academic_articles')
```



```{r}
CV %<>% print_links()
```

